import type { MailProvider } from "./types";

export const PROVIDERS: MailProvider[] = [
  {
    id: "gmail",
    name: "Gmail",
    description:
      "Compte Gmail ou Google Workspace. La méthode OAuth2 sécurise l'accès sans stocker votre mot de passe.",
    defaultImapHost: "imap.gmail.com",
    defaultImapPort: 993,
    defaultEncryption: "tls",
    authTypes: ["oauth-gmail", "imap-password"],
    preferredAuthType: "oauth-gmail",
    status: "preview",
    notes: [
      "OAuth Google à connecter (client_id + secret côté serveur).",
      "IMAP : mot de passe d'application requis (validation en 2 étapes).",
    ],
  },
  {
    id: "outlook",
    name: "Outlook / Microsoft 365",
    description:
      "Compte Outlook.com, Hotmail ou Microsoft 365. OAuth2 recommandé pour les comptes pro.",
    defaultImapHost: "outlook.office365.com",
    defaultImapPort: 993,
    defaultEncryption: "tls",
    authTypes: ["oauth-outlook", "imap-password"],
    preferredAuthType: "oauth-outlook",
    status: "preview",
    notes: [
      "OAuth Microsoft à connecter (app registration Azure AD).",
      "IMAP basic peut être désactivé sur certains tenants pro.",
    ],
  },
  {
    id: "yahoo",
    name: "Yahoo Mail",
    description: "Boîte Yahoo standard. Nécessite un mot de passe d'application.",
    defaultImapHost: "imap.mail.yahoo.com",
    defaultImapPort: 993,
    defaultEncryption: "tls",
    authTypes: ["imap-password"],
    preferredAuthType: "imap-password",
    status: "available",
    notes: ["Mot de passe d'application requis via la page de sécurité Yahoo."],
  },
  {
    id: "ovh",
    name: "OVH",
    description: "Mail OVH Pro, Exchange ou Cloud Web.",
    defaultImapHost: "ssl0.ovh.net",
    defaultImapPort: 993,
    defaultEncryption: "tls",
    authTypes: ["imap-password"],
    preferredAuthType: "imap-password",
    status: "available",
    notes: ["Serveur générique ssl0.ovh.net ou serveur de votre offre Pro."],
  },
  {
    id: "o2switch",
    name: "o2switch",
    description: "Mailbox o2switch (cPanel).",
    defaultImapHost: "",
    defaultImapPort: 993,
    defaultEncryption: "tls",
    authTypes: ["imap-password"],
    preferredAuthType: "imap-password",
    status: "available",
    notes: ["Saisissez le serveur IMAP indiqué dans votre cPanel (*.o2switch.net)."],
  },
  {
    id: "infomaniak",
    name: "Infomaniak",
    description: "Mail Infomaniak / kSuite.",
    defaultImapHost: "mail.infomaniak.com",
    defaultImapPort: 993,
    defaultEncryption: "tls",
    authTypes: ["imap-password"],
    preferredAuthType: "imap-password",
    status: "available",
    notes: ["IMAP standard mail.infomaniak.com sur 993 SSL/TLS."],
  },
  {
    id: "ionos",
    name: "Ionos",
    description: "Mail Pro et Mail Business Ionos.",
    defaultImapHost: "imap.ionos.fr",
    defaultImapPort: 993,
    defaultEncryption: "tls",
    authTypes: ["imap-password"],
    preferredAuthType: "imap-password",
    status: "available",
    notes: ["imap.ionos.fr (France) ou imap.ionos.com selon le pays du compte."],
  },
  {
    id: "custom-imap",
    name: "Autre fournisseur IMAP",
    description: "Tout serveur IMAP standard. Saisissez l'hôte, le port et le chiffrement.",
    defaultImapHost: "",
    defaultImapPort: 993,
    defaultEncryption: "tls",
    authTypes: ["imap-password"],
    preferredAuthType: "imap-password",
    status: "available",
    notes: ["Compatible IMAP/SSL ou IMAP/STARTTLS."],
  },
];

export function findProvider(id: string): MailProvider | null {
  return PROVIDERS.find((provider) => provider.id === id) ?? null;
}
